### ISSUE TITLE
error running tests on windows for RC 0.8 

### ISSUE THREAD

**Issue by cpietsch** [hfg-gmuend/zoomaker#4]
when running the tests on windows I get this error
```
python tests.py
.       downloading: 100%|███████████████████████████████████████████| 1.78k/1.78k [00:00<00:00, 1.78MiB/s]
.       downloading: 164kiB [00:00, 43.0MiB/s]
learned_embeds.bin: 100%|█████████████████████████████████████████████████████████████████| 3.82k/3.82k [00:00<?, ?B/s]
.E..
======================================================================
ERROR: test_install_huggingface_cached (__main__.ZoomakerTestCase.test_install_huggingface_cached)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\user\Documents\projects\zoomaker\test\tests.py", line 88, in test_install_huggingface_cached
    self.assertTrue(os.path.exists(filepath))
                    ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: exists: path should be string, bytes, os.PathLike or integer, not NoneType
```

It looks like [try_to_load_from_cache](https://github.com/hfg-gmuend/zoomaker/blob/6d8615274e43bda8c14213a24b8e1ff29c3044a6/test/tests.py#L83) returns None which should mean that no cache is found according to the docs:

> Returns:
        `Optional[str]` or `_CACHED_NO_EXIST`:
            Will return `None` if the file was not cached. Otherwise:
            - The exact path to the cached file if it's found in the cache
            - A special value `_CACHED_NO_EXIST` if the file does not exist at the given commit hash and this fact was
              cached.

**Comment by cpietsch** [comment]
https://huggingface.co/docs/huggingface_hub/en/guides/manage-cache

> Limitations
In order to have an efficient cache-system, huggingface-hub uses symlinks. However, symlinks are not supported on all machines. This is a known limitation especially on Windows. When this is the case, huggingface_hub do not use the blobs/ directory but directly stores the files in the snapshots/ directory instead. This workaround allows users to download and cache files from the Hub exactly the same way. Tools to inspect and delete the cache (see below) are also supported. However, the cache-system is less efficient as a single file might be downloaded several times if multiple revisions of the same repo is downloaded.


> If you want to benefit from the symlink-based cache-system on a Windows machine, you either need to [activate Developer Mode](https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development) or to run Python as an administrator.

**Comment by b-g** [comment]
Thanks!
